CREATE TABLE news (
    n_title VARCHAR(30) NOT NULL,
    n_content TEXT NOT NULL,
    n_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (n_title)
);

CREATE TABLE contacts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    c_name VARCHAR(255) NOT NULL,
    c_email VARCHAR(255) NOT NULL,
    c_message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE registration (
r_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
r_username VARCHAR(30) NOT NULL,
r_password VARCHAR(30) NOT NULL,
r_email VARCHAR(50),
r_regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

